# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:  Home
email:
description: >- # this means to ignore newlines until "baseurl:"
  This page is meant as a Blog for my current project, both personal and ongoing academic projects. I will mainly focus on topics related to my work as a Ph.D. student in multi robot systems. 
  Especially coverage planning and multi robot control in search and resque (SAR) operations.
github_username: kasperg3
linkedin_username: kaspergrontved
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
search: true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-archives
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kasper Rømer Grøntved"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Phd-Fellow @ SDU Biorobotics, MMMI, University of Southern Denmark"
  links:
  # Icons https://aksakalli.github.io/jekyll-doc-theme/docs/font-awesome/
    - label: "Odense, Denmark"
      icon: "fas fa-fw fa-map-marker"
    - label: "kang@mmmi.sdu.dk"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kang@mmmi.sdu.dk"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://blog.grontved.dk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kasperg3"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kasperg3"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kaspergrontved/"
    # - label: "Google scholar"
    # - label: ""


footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kasperg3"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/kasperg3"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kaspergrontved/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/
